version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7-management
    environment:
      RABBITMQ_DEFAULT_USER: iib
      RABBITMQ_DEFAULT_PASS: iib
    ports:
      # The RabbitMQ management console
      - 8081:15672

  iib-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-api
    command:
    - /bin/sh
    - -c
    - >-
      pip3 uninstall -y iib &&
      python3 setup.py develop --no-deps &&
      flask run --reload --host 0.0.0.0 --port 8080
    environment:
      FLASK_ENV: development
      FLASK_APP: iib/web/wsgi.py
      IIB_DEV: 'true'
    volumes:
      - ./:/src:z
    ports:
      - 8080:8080

  iib-worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-workers
    # Override the default command so that Celery auto-reloads on code changes
    command:
    - /bin/bash
    - -c
    - >-
      pip3 install watchdog[watchmedo] &&
      watchmedo auto-restart -d ./iib/workers -p '*.py' --recursive \
        -- celery -A iib.workers.tasks worker --loglevel=info
    environment:
      IIB_DEV: 'true'
    volumes:
      - ./:/src:z
    depends_on:
      - rabbitmq
